name: Continuous Integration
on: [push, pull_request, release]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          ubuntu-18.04,
          macos-11,
          macos-10.15,
          windows-2022,
          windows-2019,
          windows-2016
        ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - run: dotnet format --verify-no-changes
    - run: dotnet test /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=line
  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - run: dotnet pack --configuration Release /p:Version=${GITHUB_REF/refs\/tags\/v/}
    - run: dotnet nuget push Skitscript.Types.DotNetStandard/bin/Release/Skitscript.Types.DotNetStandard.${GITHUB_REF/refs\/tags\/v/}.nupkg --api-key ${{ secrets.NUGET_TOKEN }}
